### ISSUE TITLE
Fly flights, not simulators

### ISSUE THREAD

**Issue by brentjanderson** [alexanderson1993/thorium#20]
A flight is an instance of one or more simulators (with all the sub components), dropped into an instance of the universe. By flying flights, The same simulator can have multiple simultaneous experiences. It also gives easier management of long running flight experiences.

**Comment by alexanderson1993** [comment]
To implement this, there will have to be a flights object of some kind. I'm not sure what information would be on that object itself, other than a primary key which all other objects in the flight would reference. 

There would also have to be some kind of initialization system for the flight which would instantiate all of the objects - the simulator, stations, cards, systems, etc.

One final aspect of this would be getting the clients to know that they are part of a flight. 

What other information would be attached to the flight object itself?

**Comment by alexanderson1993** [comment]
Flights would be managed entirely on the server using ETS. No data during a flight would be stored in the database. Persistent information, such as available simulators, station configurations, assets, and missions would all be stored in the database, and would be cloned to the server when a flight was created.

You could also serialize and save a flight to the database to be loaded at a later time

This would speed up the client-server communication tremendously by leaving the database latency out of the picture entirely.

**Comment by brentjanderson** [comment]
Sounds great - I would suggest looking at Agents and not just ETS, but you're on the right track I think.

One thing that would make sense to persist to the database would be analytics and snapshots that could be used to "thaw" a flight. Really, that's all that the "clone" mechanism would do anyway is rebuild runtime information from a snapshot. So, if you can save a flight at a point in time, then thawing it would be your "clone" mechanism.

Analytics would be important to consider here too. I'll open an issue about it with ideas. 

6. 7. 2016 v 17:58, Alex <notifications@github.com>:

**Comment by alexanderson1993** [comment]
Closing because it basically is the same as #27
